### ISSUE TITLE
PSVITA is not connected error

### ISSUE THREAD

**Issue by AbyssHun** [lazydevyo/PSVitaPlay#17]
Im getting a constant popup of "PSVITA is not connected" followed by the audio symbol popping up and down repeatedly.
 

- i followed all steps accordingly, to a t
- plugin and kernel are correct
- i checked and my VITA has a valid code under its shell
- i tried disabling all webcams
-no solution i have found thus far has worked at all

does anyone have a solution for this or am i beating a dead horse

**Comment by ExtremeCaliber** [comment]
I'm sure you checked if your cable is good or not.. It could always still be plugin installation.

**Comment by AbyssHun** [comment]
> I'm sure you checked if your cable is good or not.. It could always still be plugin installation.

actually ive upgraded the problem from "not working at all" to "my vita and psvitadock crash when i reboot my vita while its attached to my pc" by moving UDUC_UMV into the uro/tai folder so i mean...step up i guess?

**Comment by AbyssHun** [comment]
welp ive managed to accidentally fix the issue myself so there, problem solved
